root: /
admin_dir: admin/
tpl: /user_data/packages/default/
admin_tpl: /user_data/packages/admin/
image_path: /upload/save_image/
root_dir: /app
root_urlpath: null
template_code: default
admin_route: admin
user_data_route: user_data
public_path: /html
public_path_realdir: /app/html
image_save_realdir: /app/html/upload/save_image
image_temp_realdir: /app/html/upload/temp_image
user_data_realdir: /app/html/user_data
block_default_realdir: /app/src/Eccube/Resource/template/default/Block
block_realdir: /app/app/template/default/Block
template_default_realdir: /app/src/Eccube/Resource/template/default
template_default_html_realdir: /app/html/template/default
template_admin_realdir: /app/src/Eccube/Resource/template/admin
template_admin_html_realdir: /app/html/template/admin
template_realdir: /app/app/template/default
template_html_realdir: /app/html/template/default
template_temp_realdir: /app/app/cache/eccube/template
csv_temp_realdir: /app/app/cache/eccube/csv
plugin_realdir: /app/app/Plugin
plugin_temp_realdir: /app/app/cache/plugin
plugin_html_realdir: /app/html/plugin
admin_urlpath: /template/admin
front_urlpath: /template/default
#image_save_urlpath: /upload/save_image
image_save_urlpath: https://bucketeer-0714e1a3-7949-48f5-a1a4-8fb59aa37e3d.s3.amazonaws.com/public
image_temp_urlpath: /upload/temp_image
user_data_urlpath: /user_data
plugin_urlpath: /plugin
